app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('welcome');
});

Route::auth();

Route::group(['prefix'=>'customer', 'middleware'=>'auth.checkrole:client', 'as'=>'customer.'], function(){
    Route::get('/order', ["as"=>"order.index", "uses"=>"CheckoutController@index"]);
    Route::get('/order/create', ["as"=>"order.create", "uses"=>"CheckoutController@create"]);
    Route::post('/order/store', ["as"=>"order.store", "uses"=>"CheckoutController@store"]);
});

Route::group(['prefix'=>'admin','middleware'=>'auth.checkrole:admin', 'as'=>'admin.'], function() {
    Route::get('/home', 'HomeController@index');

    Route::group(['prefix'=>'categorias', 'as'=>'category.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"CategoryController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"CategoryController@create"]);
        Route::get('/editar/{id}',["as"=>"edit", "uses"=>"CategoryController@edit"]);
        Route::post('/update/{id}',["as"=>"update", "uses"=>"CategoryController@update"]);
        Route::post('/store',["as"=>"store", "uses"=>"CategoryController@store"]);
    });

    Route::group(['prefix'=>'produtos', 'as'=>'product.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"ProductController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"ProductController@create"]);
        Route::get('/editar/{id}',["as"=>"edit", "uses"=>"ProductController@edit"]);
        Route::post('/update/{id}',["as"=>"update", "uses"=>"ProductController@update"]);
        Route::post('/store',["as"=>"store", "uses"=>"ProductController@store"]);
        Route::get('/destroy/{id}',["as"=>"destroy", "uses"=>"ProductController@destroy"]);
    });

    Route::group(['prefix'=>'clientes', 'as'=>'client.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"ClientController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"ClientController@create"]);
        Route::get('/editar/{id}',["as"=>"edit", "uses"=>"ClientController@edit"]);
        Route::post('/update/{id}',["as"=>"update", "uses"=>"ClientController@update"]);
        Route::post('/store',["as"=>"store", "uses"=>"ClientController@store"]);
        Route::get('/destroy/{id}',["as"=>"destroy", "uses"=>"ClientController@destroy"]);
    });

    Route::group(['prefix'=>'orders', 'as'=>'order.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"OrderController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"OrderController@create"]);
        Route::get('/editar/{id}',["as"=>"edit", "uses"=>"OrderController@edit"]);
        Route::post('/update/{id}',["as"=>"update", "uses"=>"OrderController@update"]);
        Route::post('/store',["as"=>"store", "uses"=>"OrderController@store"]);
        Route::get('/destroy/{id}',["as"=>"destroy", "uses"=>"OrderController@destroy"]);
    });

    Route::group(['prefix'=>'cupoms','as'=>'cupom.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"CupomController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"CupomController@create"]);
        Route::post('/store',["as"=>"store", "uses"=>"CupomController@store"]);
    });
});

app/Models/Client.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Client extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'user_id',
        'phone',
        'address',
        'city',
        'state',
        'zipcode'
    ];

    public function user() {
        return $this->hasOne(User::class, 'id', 'user_id');
    }

}

app/Http/Controllers/ClientController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Models\Client;
use CodeDelivery\Services\ClientService;
use Illuminate\Http\Request;

use CodeDelivery\Http\Requests;
use CodeDelivery\Http\Requests\AdminClientRequest;
use CodeDelivery\Repositories\ClientRepository;

class ClientController extends Controller
{

    private $repository;

    public function __construct(ClientRepository $repository, ClientService $clientService)
    {
        $this->repository = $repository;
        $this->clientService = $clientService;
    }

    public function index()
    {
        $clients = $this->repository->paginate(10);
        return view('admin.clients.index', compact('clients'));
    }

    public function create()
    {
        return view('admin.clients.create');
    }

    public function edit($id)
    {
        $client = $this->repository->find($id);
        return view('admin.clients.edit', compact('client'));
    }

    public function update(AdminClientRequest $request, $id)
    {
        $data = $request->all();
        $this->clientService->update($data, $id);

        return redirect()->route('admin.client.index');
    }

    public function store(AdminClientRequest $request)
    {
        $data = $request->all();
        $this->clientService->create($data);

        return redirect()->route('admin.client.index');
    }

    public function destroy($id)
    {
        $this->repository->delete($id);

        return redirect()->route('admin.client.index');
    }
}

resources/views/admin/clients/_form.blade.php
<div class="form-group">
{!! Form::label('Name','Nome:') !!}
{!! Form::text('user[name]', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Email','E-mail:') !!}
    {!! Form::email('user[email]', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Phone','Telefone:') !!}
    {!! Form::text('phone', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Address','Endereço:') !!}
    {!! Form::text('address', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('City','Cidade:') !!}
    {!! Form::text('city', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('State','Estado:') !!}
    {!! Form::text('state', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Zipcode','CEP:') !!}
    {!! Form::text('zipcode', null, ['class'=>'form-control']) !!}
</div>

resources/views/admin/clients/create.blade.php
@extends('app')

@section('content')
<div class="container">
	<h1>Criar cliente</h1>

	@include('errors._error')

	{!! Form::open(['route'=>'admin.client.store', 'class'=>'form']) !!}

	@include('admin.clients._form')

	<div class="form-group">
		{!! Form::submit('Criar', ['class'=>'btn btn-success']) !!}
	</div>

	{!! Form::close() !!}

</div>

@endsection

resources/views/admin/clients/edit.blade.php
@extends('app')

@section('content')
<div class="container">
	<h1>Editar cliente: {{$client->user->name}}</h1>

	@include('errors._error')

	{!! Form::model($client, ['route'=>['admin.client.update', $client->id]]) !!}

	@include('admin.clients._form')

	<div class="form-group">
		{!! Form::submit('Salvar', ['class'=>'btn btn-success']) !!}
	</div>

	{!! Form::close() !!}

</div>

@endsection

resources/views/admin/clients/index.blade.php
@extends('app')

@section('content')
<div class="container">
	<h1>Clientes</h1>
	<h2>
		<a href="{{ route('admin.client.create') }}" class="btn btn-default">Novo</a>
	</h2>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>E-mail</th>
				<th>Telefone</th>
				<th>Endereço</th>
				<th>Cidade</th>
				<th>Estado</th>
				<th>CEP</th>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
		@foreach($clients as $client)
			<tr>
				<td>{{ $client->id }}</td>
				<td>{{ $client->user->name }}</td>
				<td>{{ $client->user->email }}</td>
				<td>{{ $client->phone }}</td>
				<td>{{ $client->address }}</td>
				<td>{{ $client->city }}</td>
				<td>{{ $client->state }}</td>
				<td>{{ $client->zipcode }}</td>
				<td>
					<a href="{{route('admin.client.edit',['id'=>$client->id])}}" class="btn btn-default btn-sm">Editar</a>
					<a href="{{route('admin.client.destroy',['id'=>$client->id])}}" class="btn btn-danger btn-sm">Excluir</a>
				</td>
			</tr>
		</tbody>
		@endforeach 
	</table>
	{!! $clients->render() !!}
</div>

@endsection