app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('welcome');
});

Route::auth();

Route::group(['prefix'=>'customer', 'middleware'=>'auth.checkrole:client', 'as'=>'customer.'], function(){
    Route::get('/order', ["as"=>"order.index", "uses"=>"CheckoutController@index"]);
    Route::get('/order/create', ["as"=>"order.create", "uses"=>"CheckoutController@create"]);
    Route::post('/order/store', ["as"=>"order.store", "uses"=>"CheckoutController@store"]);
});

Route::group(['prefix'=>'admin','middleware'=>'auth.checkrole:admin', 'as'=>'admin.'], function() {
    Route::get('/home', 'HomeController@index');

    Route::group(['prefix'=>'categorias', 'as'=>'category.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"CategoryController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"CategoryController@create"]);
        Route::get('/editar/{id}',["as"=>"edit", "uses"=>"CategoryController@edit"]);
        Route::post('/update/{id}',["as"=>"update", "uses"=>"CategoryController@update"]);
        Route::post('/store',["as"=>"store", "uses"=>"CategoryController@store"]);
    });

    Route::group(['prefix'=>'produtos', 'as'=>'product.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"ProductController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"ProductController@create"]);
        Route::get('/editar/{id}',["as"=>"edit", "uses"=>"ProductController@edit"]);
        Route::post('/update/{id}',["as"=>"update", "uses"=>"ProductController@update"]);
        Route::post('/store',["as"=>"store", "uses"=>"ProductController@store"]);
        Route::get('/destroy/{id}',["as"=>"destroy", "uses"=>"ProductController@destroy"]);
    });

    Route::group(['prefix'=>'clientes', 'as'=>'client.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"ClientController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"ClientController@create"]);
        Route::get('/editar/{id}',["as"=>"edit", "uses"=>"ClientController@edit"]);
        Route::post('/update/{id}',["as"=>"update", "uses"=>"ClientController@update"]);
        Route::post('/store',["as"=>"store", "uses"=>"ClientController@store"]);
        Route::get('/destroy/{id}',["as"=>"destroy", "uses"=>"ClientController@destroy"]);
    });

    Route::group(['prefix'=>'orders', 'as'=>'order.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"OrderController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"OrderController@create"]);
        Route::get('/editar/{id}',["as"=>"edit", "uses"=>"OrderController@edit"]);
        Route::post('/update/{id}',["as"=>"update", "uses"=>"OrderController@update"]);
        Route::post('/store',["as"=>"store", "uses"=>"OrderController@store"]);
        Route::get('/destroy/{id}',["as"=>"destroy", "uses"=>"OrderController@destroy"]);
    });

    Route::group(['prefix'=>'cupoms','as'=>'cupom.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"CupomController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"CupomController@create"]);
        Route::post('/store',["as"=>"store", "uses"=>"CupomController@store"]);
    });
});

app/Models/Product.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Product extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'category_id',
        'name',
        'description',
        'price'
    ];

    public function category() {
        return $this->belongsTo(Category::class);
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Models\Product;
use CodeDelivery\Repositories\CategoryRepository;
use Illuminate\Http\Request;

use CodeDelivery\Http\Requests;
use CodeDelivery\Http\Requests\AdminProductRequest;
use CodeDelivery\Repositories\ProductRepository;

class ProductController extends Controller
{

    private $repository;

    public function __construct(ProductRepository $repository, CategoryRepository $categoryRepository)
    {
        $this->repository = $repository;
        $this->categoryRepository = $categoryRepository;
    }

    public function index()
    {
        $products = $this->repository->paginate(10);

        return view('admin.products.index', compact('products'));
    }

    public function create()
    {
        $categories = $this->categoryRepository->lists('name','id');
        return view('admin.products.create',compact('categories'));
    }

    public function edit($id)
    {
        $product = $this->repository->find($id);
        $categories = $this->categoryRepository->get('name','id');

        return view('admin.products.edit', compact(['product','categories']));
    }

    public function update(AdminProductRequest $request, $id)
    {
        $data = $request->all();
        $this->repository->update($data, $id);

        return redirect()->route('admin.product.index');
    }

    public function store(AdminProductRequest $request)
    {
        $data = $request->all();
        $this->repository->create($data);

        return redirect()->route('admin.product.index');
    }

    public function destroy($id)
    {
        $this->repository->delete($id);

        return redirect()->route('admin.product.index');
    }
}

resources/views/admin/products/_form.blade.php
<div class="form-group">
{!! Form::label('Name','Nome:') !!}
{!! Form::text('name', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Category','Categoria:') !!}
    {!! Form::select('category_id', $categories, null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Price','Preço:') !!}
    {!! Form::number('price', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Description','Descrição:') !!}
    {!! Form::textarea('description', null, ['class'=>'form-control']) !!}
</div>

resources/views/admin/products/create.blade.php
@extends('app')

@section('content')
<div class="container">
	<h1>Criar produto</h1>

	@include('errors._error');

	{!! Form::open(['route'=>'admin.product.store', 'class'=>'form']) !!}

	@include('admin.products._form');

	<div class="form-group">
		{!! Form::submit('Criar produto', ['class'=>'btn btn-success']) !!}
	</div>

	{!! Form::close() !!}

</div>

@endsection

resources/views/admin/products/edit.blade.php
@extends('app')

@section('content')
<div class="container">
	<h1>Editar produto: {{$product->name}}</h1>

	@include('errors._error')

	{!! Form::model($product, ['route'=>['admin.product.update', $product->id]]) !!}

	@include('admin.products._form')

	<div class="form-group">
		{!! Form::submit('Salvar', ['class'=>'btn btn-success']) !!}
	</div>

	{!! Form::close() !!}

</div>

@endsection

resources/views/admin/products/index.blade.php
@extends('app')

@section('content')
<div class="container">
	<h1>Produtos</h1>
	<h2>
		<a href="{{ route('admin.product.create') }}" class="btn btn-default">Criar produto</a>
	</h2>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Categoria</th>
				<th>Preço</th>
				<th>Ação</th>
			</tr>
		</thead>
		<tbody>
		@foreach($products as $product)
			<tr>
				<td>{{ $product->id }}</td>
				<td>{{ $product->name }}</td>
				<td>{{ $product->category->name }}</td>
				<td>{{ $product->price }}</td>
				<td>
					<a href="{{route('admin.product.edit',['id'=>$product->id])}}" class="btn btn-default btn-sm">Editar</a>
					<a href="{{route('admin.product.destroy',['id'=>$product->id])}}" class="btn btn-danger btn-sm">Excluir</a>
				</td>
			</tr>
		</tbody>
		@endforeach 
	</table>
	{!! $products->render() !!}
</div>

@endsection