app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('welcome');
});

Route::auth();

Route::group(['prefix'=>'customer', 'middleware'=>'auth.checkrole:client', 'as'=>'customer.'], function(){
    Route::get('/order', ["as"=>"order.index", "uses"=>"CheckoutController@index"]);
    Route::get('/order/create', ["as"=>"order.create", "uses"=>"CheckoutController@create"]);
    Route::post('/order/store', ["as"=>"order.store", "uses"=>"CheckoutController@store"]);
});

Route::group(['prefix'=>'admin','middleware'=>'auth.checkrole:admin', 'as'=>'admin.'], function() {
    Route::get('/home', 'HomeController@index');

    Route::group(['prefix'=>'categorias', 'as'=>'category.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"CategoryController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"CategoryController@create"]);
        Route::get('/editar/{id}',["as"=>"edit", "uses"=>"CategoryController@edit"]);
        Route::post('/update/{id}',["as"=>"update", "uses"=>"CategoryController@update"]);
        Route::post('/store',["as"=>"store", "uses"=>"CategoryController@store"]);
    });

    Route::group(['prefix'=>'produtos', 'as'=>'product.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"ProductController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"ProductController@create"]);
        Route::get('/editar/{id}',["as"=>"edit", "uses"=>"ProductController@edit"]);
        Route::post('/update/{id}',["as"=>"update", "uses"=>"ProductController@update"]);
        Route::post('/store',["as"=>"store", "uses"=>"ProductController@store"]);
        Route::get('/destroy/{id}',["as"=>"destroy", "uses"=>"ProductController@destroy"]);
    });

    Route::group(['prefix'=>'clientes', 'as'=>'client.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"ClientController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"ClientController@create"]);
        Route::get('/editar/{id}',["as"=>"edit", "uses"=>"ClientController@edit"]);
        Route::post('/update/{id}',["as"=>"update", "uses"=>"ClientController@update"]);
        Route::post('/store',["as"=>"store", "uses"=>"ClientController@store"]);
        Route::get('/destroy/{id}',["as"=>"destroy", "uses"=>"ClientController@destroy"]);
    });

    Route::group(['prefix'=>'orders', 'as'=>'order.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"OrderController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"OrderController@create"]);
        Route::get('/editar/{id}',["as"=>"edit", "uses"=>"OrderController@edit"]);
        Route::post('/update/{id}',["as"=>"update", "uses"=>"OrderController@update"]);
        Route::post('/store',["as"=>"store", "uses"=>"OrderController@store"]);
        Route::get('/destroy/{id}',["as"=>"destroy", "uses"=>"OrderController@destroy"]);
    });

    Route::group(['prefix'=>'cupoms','as'=>'cupom.'], function(){
        Route::get('/', ["as"=>"index", "uses"=>"CupomController@index"]);
        Route::get('/criar',["as"=>"create", "uses"=>"CupomController@create"]);
        Route::post('/store',["as"=>"store", "uses"=>"CupomController@store"]);
    });
});

app/Models/Category.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Category extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
    	'name'
    ];

    public function products() {
    	return $this->hasMany(Product::class);
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace CodeDelivery\Http\Controllers;

use Illuminate\Http\Request;

use CodeDelivery\Http\Requests;
use CodeDelivery\Http\Requests\AdminCategoryRequest;
use CodeDelivery\Repositories\CategoryRepository;

class CategoryController extends Controller
{

	private $repository;

	public function __construct(CategoryRepository $repository)
	{
		$this->repository = $repository;
	}

    public function index()
    {	
    	$categories = $this->repository->paginate(10);

        return view('admin.categories.index', compact('categories'));
    }

    public function create()
    {
    	return view('admin.categories.create');
    }

    public function edit($id)
    {
        $category = $this->repository->find($id);

        return view('admin.categories.edit', compact('category'));
    }

    public function update(AdminCategoryRequest $request, $id)
    {
        $data = $request->all();
        $this->repository->update($data, $id);

        return redirect()->route('admin.category.index');
    }

    public function store(AdminCategoryRequest $request)
    {
    	$data = $request->all();
    	$this->repository->create($data);
    	
    	return redirect()->route('admin.category.index');
    }
}

resources/views/admin/categories/_form.blade.php
<div class="form-group">
{!! Form::label('Name','Nome:') !!}
{!! Form::text('name', null, ['class'=>'form-control']) !!}
</div>

resources/views/admin/categories/create.blade.php
@extends('app')

@section('content')
<div class="container">
	<h1>Criar categoria</h1>

	@include('errors._error');

	{!! Form::open(['route'=>'admin.category.store', 'class'=>'form']) !!}

	@include('admin.categories._form');

	<div class="form-group">
		{!! Form::submit('Criar categoria', ['class'=>'btn btn-success']) !!}
	</div>

	{!! Form::close() !!}

</div>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('app')

@section('content')
<div class="container">
	<h1>Editar categoria: {{$category->name}}</h1>

	@include('errors._error');

	{!! Form::model($category, ['route'=>['admin.category.update', $category->id]]) !!}

	@include('admin.categories._form');

	<div class="form-group">
		{!! Form::submit('Salvar categoria', ['class'=>'btn btn-success']) !!}
	</div>

	{!! Form::close() !!}

</div>

@endsection

resources/views/admin/categories/index.blade.php
@extends('app')

@section('content')
<div class="container">
	<h1>Categorias</h1>
	<h2>
		<a href="{{ route('admin.category.create') }}" class="btn btn-default">Criar categoria</a>
	</h2>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Ação</th>
			</tr>
		</thead>
		<tbody>
		@foreach($categories as $category)
			<tr>
				<td>{{ $category->id }}</td>
				<td>{{ $category->name }}</td>
				<td>
					<a href="{{route('admin.category.edit',['id'=>$category->id])}}" class="btn btn-default btn-sm">Editar</a>
				</td>
			</tr>
		</tbody>
		@endforeach 
	</table>
	{!! $categories->render() !!}
</div>

@endsection